title: Ramesh
description: PhD Research Scholar | Data Science | Deep Learning
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: Ramesh Eerapagula
  avatar: /assets/profile.jpg
  bio: "Data Science • Machine Learning • Deep Learning"
  location: India
  links:
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/Ramesh5591
    - label: Email
      icon: fas fa-envelope
      url: mailto:ramesheerapagula76@gmail.com
